### ISSUE TITLE
Consider using RustlerPrecompiled

### ISSUE THREAD

**Issue by philss** [mjaric/tds-encoding#5]
Thanks for this project.

I would like to propose the adoption of [`RustlerPrecompiled`](https://hexdocs.pm/rustler_precompiled/RustlerPrecompiled.html), so more users could benefit from this without the need to have all the Rust toolchain installed.

I can setup the project if you agree.
The only requirement after that is to follow the release process by the Hex publisher.

**Comment by philss** [comment]
PS: this is also related to a discussion started in https://github.com/philss/floki/issues/116#issuecomment-1198100579

cc @nuno84

**Comment by moogle19** [comment]
@philss 
I just created a new repo with `RustlerPrecompiled` (since I only can push, but not edit the CI settings on this repo).
I published it to hex here: https://hex.pm/packages/excoding

**Comment by philss** [comment]
@moogle19 awesome! Thank you! :purple_heart:

**Comment by philss** [comment]
@nuno84 can you try with this new package? https://hex.pm/packages/excoding
Here is the docs: https://hexdocs.pm/excoding/Excoding.html

**Comment by nuno84** [comment]
It works very well now with excoding.
Thank you @philss and @moogle19 
Great work.
